[workspace]

members = [
  "tokio",
  "tokio-codec",
  "tokio-compat",
  "tokio-executor",
  "tokio-fs",
  "tokio-io",
  "tokio-macros",
  "tokio-net",
  "tokio-sync",
  "tokio-test",
  "tokio-timer",
  "tokio-tls",
  "build-tests",
]
