[package]
name = "tokio-compat"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
futures-01 = ["futures_01"]
futures-io = ["tokio-io", "futures-io"]

[dependencies]
pin-project = "0.4"
futures_01 = { package = "futures", version = "0.1", optional = "true" }
futures_03 = { package = "futures", version = "0.1", optional = "true" }
tokio_io = {version = "0.2.0-alpha.6", optional = true }
